export enum Sector {
	RestaurantCafeSnack = 0,
	Supermarket = 1,
	FashionClothing = 2,
	Furniture = 3,
	HardwareStore = 4,
	Electronics = 5,
	DrugstorePerfumeryPharmacy = 6,
	BabyChildToys = 7,
	WatchesAndJewellery = 8,
	TravelHoliday = 9,
	CarMotorcycle = 10,
	SportHealthFitness = 11,
	PhotoVideo = 12,
	PetshopsPetSupplies = 13,
	GardenPlants = 14,
	Optics = 15,
	FinanceBanksInsurance = 16,
	Service = 17,
	Renovation = 18
}
